version: '3'

services:
  mysql:
    container_name: unidesc-database
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'unidesc'
      MYSQL_USER: 'unidesc'
      MYSQL_PASSWORD: 'unidesc'
